import java.nio.charset.StandardCharsets
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption

plugins {
    id 'java'
    id 'idea'
}

group = 'com.example.avoidmod'
version = project.properties.version

//====================//
//=== Repositories ===//
//====================//

repositories {
    mavenCentral()

    flatDir {
        dirs "libs"
    }
}

//=====================//
//=== Local Plugins ===//
//=====================//

apply from: rootProject.file("build_avoid.gradle")
apply from: rootProject.file("build_launchers.gradle")

//============//
//=== Base ===//
//============//

base {
    archivesName = project.properties.jar_name
}

//====================//
//=== Dependencies ===//
//====================//

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    implementation "pl.olafcio:avoid:${project.properties.avoid_version}"

    compileOnly "org.joml:joml:1.10.8"
    compileOnly "org.jetbrains:annotations:20.1.0"
}

//=================//
//=== Resources ===//
//=================//

private String output(String... command) {
    var proc = new ProcessBuilder().command(command)
                                            .start()

    proc.waitFor()

    return new String(proc.in.readAllBytes(), StandardCharsets.UTF_8).substring(0, 40)
}

private String getBranch()            { return output("git", "branch", "--no-color", "--no-abbrev", "--show-current") }
private String getCommitHash()        { return output("git", "log", getBranch(), "-1", "--format=%H")                 }
private String getCommitAmount()      { return output("git", "rev-list", "--count", getBranch())                      }
private String getCommitAmountTotal() { return output("git", "rev-list", "--count", "--all")                          }

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    inputs.properties.putAll(project.properties)

    inputs.property "branch", getBranch()
    inputs.property "commit_hash", getCommitHash()
    inputs.property "commit_amount", getCommitAmount()
    inputs.property "commit_amount_total", getCommitAmountTotal()

    filteringCharset "UTF-8"
    filesMatching(["avoid.mod.json"]) {
        expand inputs.properties
    }
}

//====================//
//=== Output Setup ===//
//====================//

jar {
    from("LICENSE") {
        rename { "${it}_${project.properties.jarName}" }
    }

    if (project.file('src/main/resources/META-INF/MANIFEST.MF').isFile()) {
        manifest {
            from 'src/main/resources/META-INF/MANIFEST.MF'
        }
    }
}

//========================================//
//===       Rename to .avoid.zip       ===//
//===  (silences modloaders warnings)  ===//
//========================================//

private Path getOldJAR() {
    return tasks.jar.archiveFile.get().asFile.toPath()
}

private Path getAvoidZIP() {
    var path = getOldJAR()
    var str = path.toString().split("/").last()

    return path.getParent().resolve(str.substring(0, str.length() - 4) + ".avoid.zip")
}

ext.buildFile = getAvoidZIP()

tasks.jar.doLast {
    Files.move(getOldJAR(), getAvoidZIP(), StandardCopyOption.REPLACE_EXISTING)
}

//============//
//=== Java ===//
//============//

def targetJavaVersion = Integer.parseInt((String) project.property("java_version"))

tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.

    it.options.encoding = "UTF-8"

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)

    if (System.getProperty("gen_sources") != null)
        withSourcesJar()
}

//=============//
//=== Tests ===//
//=============//

test {
    useJUnitPlatform()
}
